create extension if not exists pgcrypto;
create table organisations(id uuid primary key default gen_random_uuid(),name text not null,address text,bank_name text,bank_branch text,bank_account text,created_at timestamptz default now());
create table employees(id uuid primary key default gen_random_uuid(),organisation_id uuid not null references organisations on delete cascade,employee_code text not null,full_name text not null,designation text,department text,joining_date date,leaving_date date,pan text,uan text,esi_number text,bank_name text,bank_branch text,bank_account text,ifsc text,permitted_leave_per_month numeric(5,2) default 1,status text default 'active' check(status in('active','inactive')),unique(organisation_id,employee_code));
create table salary_structures(id uuid primary key default gen_random_uuid(),employee_id uuid not null references employees on delete cascade,effective_from date not null,basic numeric(14,2) default 0,da numeric(14,2) default 0,hra numeric(14,2) default 0,other_allowance numeric(14,2) default 0,epf numeric(14,2) default 0,esi numeric(14,2) default 0,professional_tax numeric(14,2) default 0,tds numeric(14,2) default 0,active boolean default true);
create table attendance(id uuid primary key default gen_random_uuid(),employee_id uuid not null references employees on delete cascade,payroll_month date not null,calendar_days numeric(5,2) not null,present_days numeric(5,2) not null,leave_days numeric(5,2) default 0,permitted_leave numeric(5,2) default 0,lop_days numeric(5,2) default 0,lop_amount_override numeric(14,2),unique(employee_id,payroll_month));
create table advances(id uuid primary key default gen_random_uuid(),employee_id uuid not null references employees on delete cascade,advance_type text not null check(advance_type in('loan','salary_advance')),sanction_date date not null,payroll_month date,sanctioned_amount numeric(14,2) not null,outstanding_amount numeric(14,2) not null,instalment_amount numeric(14,2) not null,number_of_instalments int,bypass_recovery boolean default false,bypass_reason text,status text default 'active' check(status in('active','closed','cancelled')),terms text);
create table payroll_runs(id uuid primary key default gen_random_uuid(),organisation_id uuid not null references organisations on delete cascade,payroll_month date not null,status text default 'draft' check(status in('draft','finalised','paid','cancelled')),payment_date date,gross_total numeric(16,2) default 0,deduction_total numeric(16,2) default 0,net_total numeric(16,2) default 0,finalised_at timestamptz,created_at timestamptz default now(),unique(organisation_id,payroll_month));
create table payroll_lines(id uuid primary key default gen_random_uuid(),payroll_run_id uuid not null references payroll_runs on delete cascade,employee_id uuid not null references employees,basic numeric(14,2) default 0,da numeric(14,2) default 0,hra numeric(14,2) default 0,other_allowance numeric(14,2) default 0,gross numeric(14,2) default 0,epf numeric(14,2) default 0,esi numeric(14,2) default 0,professional_tax numeric(14,2) default 0,tds numeric(14,2) default 0,lop_days numeric(5,2) default 0,lop_amount numeric(14,2) default 0,loan_recovery numeric(14,2) default 0,salary_advance_recovery numeric(14,2) default 0,other_deduction numeric(14,2) default 0,net_pay numeric(14,2) default 0,unique(payroll_run_id,employee_id));
create table advance_recoveries(id uuid primary key default gen_random_uuid(),advance_id uuid not null references advances,payroll_line_id uuid not null references payroll_lines on delete cascade,amount numeric(14,2) not null,recovery_date date,bypassed boolean default false);
create table audit_log(id bigint generated always as identity primary key,organisation_id uuid references organisations,table_name text not null,record_id text,action text not null,old_data jsonb,new_data jsonb,changed_by uuid default auth.uid(),changed_at timestamptz default now());
create index employees_org_idx on employees(organisation_id,status);create index attendance_month_idx on attendance(payroll_month,employee_id);create index advances_employee_idx on advances(employee_id,status);create index payroll_runs_month_idx on payroll_runs(organisation_id,payroll_month);
alter table organisations enable row level security;alter table employees enable row level security;alter table salary_structures enable row level security;alter table attendance enable row level security;alter table advances enable row level security;alter table payroll_runs enable row level security;alter table payroll_lines enable row level security;alter table advance_recoveries enable row level security;alter table audit_log enable row level security;
-- Add organisation-membership RLS policies after enabling Supabase Auth. Never use the service-role key in browser code.
