const $=id=>document.getElementById(id);const showMessage=(text,type='danger')=>{const el=$('loginMessage');el.className=`alert alert-${type} py-2 mb-3`;el.textContent=text;el.classList.remove('d-none')};const hideMessage=()=>$('loginMessage').classList.add('d-none');
function togglePanel(panel){$('loginForm').classList.add('d-none');$('forgotPasswordPanel').classList.add('d-none');$('setPasswordPanel').classList.add('d-none');$('loginFooter').classList.toggle('d-none',panel!=='login');$(panel==='login'?'loginForm':panel).classList.remove('d-none')}
document.addEventListener('DOMContentLoaded',async()=>{if(!window.sb)return showMessage('Supabase configuration is missing. Update js/config.js.');document.querySelectorAll('[data-toggle]').forEach(button=>button.onclick=()=>{const input=$(button.dataset.toggle),icon=button.querySelector('i');input.type=input.type==='password'?'text':'password';icon.className=input.type==='password'?'bi bi-eye':'bi bi-eye-slash'});
 const savedEmail=localStorage.getItem('payroll_remembered_email');if(savedEmail){$('email').value=savedEmail;$('rememberMe').checked=true}
 const query=new URLSearchParams(location.search),hash=new URLSearchParams(location.hash.replace(/^#/,'')),code=query.get('code'),type=query.get('type')||hash.get('type'),hasToken=hash.get('access_token');if(code||hasToken){showMessage('Verifying link, please wait…','info');if(code){const {error}=await sb.auth.exchangeCodeForSession(code);if(error)return showMessage('The link has expired or was already used. Please request a new link.')}else await new Promise(resolve=>setTimeout(resolve,500));const {data:{session}}=await sb.auth.getSession();if(!session)return showMessage('Could not establish a session from this link.');const mustSetPassword=['invite','recovery'].includes(type)||session.user.user_metadata?.is_vendor_owner||session.user.user_metadata?.is_staff_member||sessionStorage.getItem('payroll_password_recovery')==='1';if(mustSetPassword){hideMessage();togglePanel('setPasswordPanel');if(type==='recovery'||sessionStorage.getItem('payroll_password_recovery')==='1'){$('setPasswordIntro').innerHTML='<i class="bi bi-key me-1"></i>Enter a new password for your account.';$('setPasswordLabel').textContent='Reset Password & Sign In'}return}location.href='dashboard.html';return}
 const {data:{session}}=await sb.auth.getSession();if(session){location.href='dashboard.html';return}
 $('loginForm').onsubmit=async e=>{e.preventDefault();hideMessage();const email=$('email').value.trim(),password=$('password').value;if(!email||!password)return showMessage('Please enter both email and password.');$('loginBtn').disabled=true;$('loginSpinner').classList.remove('d-none');const {error}=await sb.auth.signInWithPassword({email,password});$('loginBtn').disabled=false;$('loginSpinner').classList.add('d-none');if(error)return showMessage(error.message);if($('rememberMe').checked)localStorage.setItem('payroll_remembered_email',email);else localStorage.removeItem('payroll_remembered_email');location.href='dashboard.html'};
 $('forgotPasswordLink').onclick=e=>{e.preventDefault();hideMessage();$('forgotEmail').value=$('email').value.trim();togglePanel('forgotPasswordPanel');$('forgotEmail').focus()};$('backToLogin').onclick=e=>{e.preventDefault();hideMessage();togglePanel('login')};$('sendResetBtn').onclick=async()=>{const email=$('forgotEmail').value.trim();if(!email)return showMessage('Please enter your email address.');$('sendResetBtn').disabled=true;$('resetSpinner').classList.remove('d-none');sessionStorage.setItem('payroll_password_recovery','1');const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/index.html?type=recovery'});$('sendResetBtn').disabled=false;$('resetSpinner').classList.add('d-none');showMessage(error?error.message:'If an account exists for this email, a reset link has been sent.',error?'danger':'success')};
 $('setPasswordBtn').onclick=async()=>{const password=$('newPassword').value,confirm=$('confirmPassword').value;if(password.length<8)return showMessage('Password must be at least 8 characters.');if(password!==confirm)return showMessage('Passwords do not match.');$('setPasswordBtn').disabled=true;$('setPasswordSpinner').classList.remove('d-none');const {error}=await sb.auth.updateUser({password});$('setPasswordBtn').disabled=false;$('setPasswordSpinner').classList.add('d-none');if(error)return showMessage(error.message);sessionStorage.removeItem('payroll_password_recovery');location.href='dashboard.html'}});
