const alertBox=(message,type='success')=>adminAlert.innerHTML=`<div class="alert alert-${type}">${message}</div>`;
let vendors=[];
function resetVendorForm(){vendorForm.reset();vendorForm.elements.id.value='';vendorFormTitle.textContent='Create Vendor';vendorSave.innerHTML='<i class="bi bi-building-add"></i> Create vendor & invite owner';vendorCancel.classList.add('d-none')}
async function loadVendors(){const {data,error}=await sb.from('tenants').select('id,name,owner_email,status,subscriptions(id,plan,valid_to,status)').order('created_at',{ascending:false});if(error)return alertBox(error.message,'danger');vendors=data||[];vendorRows.innerHTML=vendors.map(v=>{const s=v.subscriptions?.[0]||{};return `<tr><td>${v.name}</td><td>${v.owner_email||'—'}</td><td>${s.plan||'—'}</td><td>${s.valid_to||'—'}</td><td><span class="badge bg-${v.status==='active'?'success':'secondary'}">${v.status}</span></td><td class="d-flex gap-1 flex-wrap"><button class="btn btn-sm btn-outline-primary open-payroll" data-id="${v.id}">Open Payroll</button><button class="btn btn-sm btn-outline-secondary edit-vendor" data-id="${v.id}">Edit</button><button class="btn btn-sm btn-outline-warning status" data-id="${v.id}" data-status="${v.status==='active'?'suspended':'active'}">${v.status==='active'?'Suspend':'Activate'}</button><button class="btn btn-sm btn-outline-danger delete-vendor" data-id="${v.id}">Delete</button></td></tr>`}).join('');
 document.querySelectorAll('.open-payroll').forEach(b=>b.onclick=()=>{sessionStorage.setItem('platform_tenant_id',b.dataset.id);location.href='dashboard.html'});
 document.querySelectorAll('.edit-vendor').forEach(b=>b.onclick=()=>{const v=vendors.find(x=>x.id===b.dataset.id),s=v.subscriptions?.[0]||{};vendorForm.elements.id.value=v.id;vendorForm.elements.name.value=v.name;vendorForm.elements.email.value=v.owner_email||'';vendorForm.elements.plan.value=s.plan||'trial';vendorForm.elements.valid_to.value=s.valid_to||'';vendorFormTitle.textContent='Edit Vendor';vendorSave.textContent='Save vendor changes';vendorCancel.classList.remove('d-none');scrollTo({top:0,behavior:'smooth'})});
 document.querySelectorAll('.status').forEach(b=>b.onclick=async()=>{const {error}=await sb.from('tenants').update({status:b.dataset.status}).eq('id',b.dataset.id);error?alertBox(error.message,'danger'):loadVendors()});
 document.querySelectorAll('.delete-vendor').forEach(b=>b.onclick=async()=>{const v=vendors.find(x=>x.id===b.dataset.id);if(!confirm(`Permanently delete ${v.name} and all its payroll data? This cannot be undone.`))return;const typed=prompt('Type DELETE to confirm');if(typed!=='DELETE')return;const {data,error}=await sb.functions.invoke('admin-users',{body:{action:'delete_vendor',tenant_id:v.id}});if(error||data?.error)return alertBox(data?.error||error.message,'danger');if(sessionStorage.getItem('platform_tenant_id')===v.id)sessionStorage.removeItem('platform_tenant_id');alertBox(data.message);loadVendors()})}
document.addEventListener('DOMContentLoaded',async()=>{const s=await requirePayrollSession();if(!s)return;const {data:isAdmin}=await sb.rpc('is_platform_admin');if(!isAdmin){location.href='dashboard.html';return}vendorCancel.onclick=resetVendorForm;vendorForm.onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;const payload=Object.fromEntries(new FormData(vendorForm));try{if(payload.id){const vendor=vendors.find(v=>v.id===payload.id),subscription=vendor.subscriptions?.[0];const {error:tenantError}=await sb.from('tenants').update({name:payload.name,owner_email:payload.email}).eq('id',payload.id);if(tenantError)throw tenantError;const subscriptionData={tenant_id:payload.id,plan:payload.plan,valid_to:payload.valid_to||null};const response=subscription?await sb.from('subscriptions').update(subscriptionData).eq('id',subscription.id):await sb.from('subscriptions').insert(subscriptionData);if(response.error)throw response.error;alertBox('Vendor updated successfully.');resetVendorForm();await loadVendors();return}const {data,error}=await sb.functions.invoke('admin-users',{body:{action:'create_vendor',...payload}});if(error)throw error;if(data?.error)throw new Error(data.error);alertBox(data?.message||'Vendor created and invitation sent.');resetVendorForm();await loadVendors()}catch(error){const unreachable=/Failed to send a request|Failed to fetch/i.test(error.message);alertBox(unreachable?'The Supabase admin-users Edge Function is not deployed or is unreachable. Deploy it in Supabase Edge Functions, then try again.':error.message,'danger')}finally{button.disabled=false}};loadVendors()});
