const alertBox=(message,type='success')=>adminAlert.innerHTML=`<div class="alert alert-${type}">${message}</div>`;
let vendors=[],prices={monthly:0,quarterly:0,annual:0};const rupees=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(+n||0);
function addMonths(date,months){const d=new Date(date+'T00:00:00');d.setMonth(d.getMonth()+months);return d.toISOString().slice(0,10)}
function resetVendorForm(){vendorForm.reset();vendorForm.elements.id.value='';vendorFormTitle.textContent='Create Vendor';vendorSave.innerHTML='<i class="bi bi-building-add"></i> Create vendor & invite owner';vendorCancel.classList.add('d-none')}
async function loadPrices(){const {data,error}=await sb.from('subscription_prices').select('billing_cycle,amount');if(error)return alertBox(error.message,'danger');for(const row of data||[])prices[row.billing_cycle]=+row.amount;for(const cycle of Object.keys(prices))pricingForm.elements[cycle].value=prices[cycle]}
async function loadVendors(){const {data,error}=await sb.from('tenants').select('id,name,owner_email,status,subscriptions(id,plan,amount,valid_from,valid_to,status)').order('created_at',{ascending:false});if(error)return alertBox(error.message,'danger');vendors=data||[];vendorRows.innerHTML=vendors.map(v=>{const s=(v.subscriptions||[]).sort((a,b)=>String(b.valid_to||'').localeCompare(String(a.valid_to||'')))[0]||{};return `<tr><td>${v.name}</td><td>${v.owner_email||'—'}</td><td>${s.plan||'—'}</td><td>${rupees(s.amount)}</td><td>${s.valid_to||'—'}</td><td><span class="badge bg-${v.status==='active'&&s.status==='active'?'success':'secondary'}">${v.status==='active'?(s.status||'—'):v.status}</span></td><td class="d-flex gap-1 flex-wrap"><button class="btn btn-sm btn-outline-primary open-payroll" data-id="${v.id}">Open Payroll</button><button class="btn btn-sm btn-outline-secondary edit-vendor" data-id="${v.id}">Edit / Renew</button><button class="btn btn-sm btn-outline-warning status" data-id="${v.id}" data-status="${v.status==='active'?'suspended':'active'}">${v.status==='active'?'Suspend':'Activate'}</button><button class="btn btn-sm btn-outline-danger delete-vendor" data-id="${v.id}">Delete</button></td></tr>`}).join('');
 document.querySelectorAll('.open-payroll').forEach(b=>b.onclick=()=>{sessionStorage.setItem('platform_tenant_id',b.dataset.id);location.href='dashboard.html'});
 document.querySelectorAll('.edit-vendor').forEach(b=>b.onclick=()=>{const v=vendors.find(x=>x.id===b.dataset.id),s=(v.subscriptions||[]).sort((a,b)=>String(b.valid_to||'').localeCompare(String(a.valid_to||'')))[0]||{};vendorForm.elements.id.value=v.id;vendorForm.elements.name.value=v.name;vendorForm.elements.email.value=v.owner_email||'';vendorForm.elements.plan.value=['monthly','quarterly','annual'].includes(s.plan)?s.plan:'monthly';vendorForm.elements.activate_subscription.checked=false;vendorFormTitle.textContent='Edit / Renew Vendor';vendorSave.textContent='Save vendor changes';vendorCancel.classList.remove('d-none');scrollTo({top:pricingForm.closest('section').offsetHeight,behavior:'smooth'})});
 document.querySelectorAll('.status').forEach(b=>b.onclick=async()=>{const {error}=await sb.from('tenants').update({status:b.dataset.status}).eq('id',b.dataset.id);error?alertBox(error.message,'danger'):loadVendors()});
 document.querySelectorAll('.delete-vendor').forEach(b=>b.onclick=async()=>{const v=vendors.find(x=>x.id===b.dataset.id);if(!confirm(`Permanently delete ${v.name} and all its payroll data? This cannot be undone.`))return;if(prompt('Type DELETE to confirm')!=='DELETE')return;const {data,error}=await sb.functions.invoke('admin-users',{body:{action:'delete_vendor',tenant_id:v.id}});if(error||data?.error)return alertBox(data?.error||error.message,'danger');if(sessionStorage.getItem('platform_tenant_id')===v.id)sessionStorage.removeItem('platform_tenant_id');alertBox(data.message);loadVendors()})}
document.addEventListener('DOMContentLoaded',async()=>{const s=await requirePayrollSession();if(!s)return;const {data:isAdmin}=await sb.rpc('is_platform_admin');if(!isAdmin){location.href='dashboard.html';return}
 pricingForm.onsubmit=async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(pricingForm));const rows=['monthly','quarterly','annual'].map(c=>({billing_cycle:c,amount:+values[c],updated_at:new Date().toISOString(),updated_by:s.session.user.id}));const {error}=await sb.from('subscription_prices').upsert(rows);if(error)return alertBox(error.message,'danger');prices=Object.fromEntries(rows.map(r=>[r.billing_cycle,r.amount]));alertBox('Subscription prices saved.')};
 vendorCancel.onclick=resetVendorForm;vendorForm.onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;const payload=Object.fromEntries(new FormData(vendorForm));try{if(payload.id){const {error:tenantError}=await sb.from('tenants').update({name:payload.name,owner_email:payload.email}).eq('id',payload.id);if(tenantError)throw tenantError;if(payload.activate_subscription==='yes'){const months={monthly:1,quarterly:3,annual:12}[payload.plan],today=new Date().toISOString().slice(0,10),subscriptionData={tenant_id:payload.id,plan:payload.plan,valid_from:today,valid_to:addMonths(today,months),status:'active',amount:prices[payload.plan]||0,activated_at:new Date().toISOString()};const {error}=await sb.from('subscriptions').insert(subscriptionData);if(error)throw error}alertBox(payload.activate_subscription==='yes'?'Vendor subscription activated.':'Vendor details updated.');resetVendorForm();await loadVendors();return}
 const {data,error}=await sb.functions.invoke('admin-users',{body:{action:'create_vendor',name:payload.name,email:payload.email}});if(error)throw error;if(data?.error)throw new Error(data.error);alertBox(data?.message||'Vendor created with one-month trial and invitation sent.');resetVendorForm();await loadVendors()}catch(error){const unreachable=/Failed to send a request|Failed to fetch/i.test(error.message);alertBox(unreachable?'The Supabase admin-users Edge Function is not deployed or is unreachable. Deploy it in Supabase Edge Functions, then try again.':error.message,'danger')}finally{button.disabled=false}};
 await loadPrices();await loadVendors()});
