const ua=(m,t='success')=>userAlert.innerHTML=`<div class="alert alert-${t}">${m}</div>`;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.addEventListener('DOMContentLoaded',async()=>{const s=await requirePayrollSession();if(!s)return;if(!['vendor_admin','platform_admin'].includes(s.role)){location.href='dashboard.html';return}let users=[];let {data:roles,error:rolesError}=await sb.from('roles').select('*').eq('tenant_id',s.tenantId).order('role_name');if(rolesError)return ua(rolesError.message,'danger');if(!roles?.length){const defaults=[{tenant_id:s.tenantId,role_name:'vendor_admin',full_access:true,permissions:[]},{tenant_id:s.tenantId,role_name:'payroll_manager',full_access:false,permissions:['staff','attendance','loans','payroll','reports','settings']},{tenant_id:s.tenantId,role_name:'payroll_user',full_access:false,permissions:['staff','attendance','payroll']},{tenant_id:s.tenantId,role_name:'viewer',full_access:false,permissions:['reports']}];const {data:seeded,error:seedError}=await sb.from('roles').upsert(defaults,{onConflict:'tenant_id,role_name'}).select();if(seedError)return ua(seedError.message,'danger');roles=seeded}roleSelect.innerHTML=(roles||[]).map(r=>`<option value="${esc(r.role_name)}">${esc(r.role_name)}</option>`).join('');roleCards.innerHTML=(roles||[]).map(r=>`<div class="border rounded p-3 mb-2"><b>${esc(r.role_name)}</b><div class="text-muted small">${r.full_access?'Full access':esc((r.permissions||[]).join(', '))}</div></div>`).join('');
 const profile=x=>Array.isArray(x.user_profiles)?x.user_profiles[0]:x.user_profiles;const invoke=async body=>{const {data,error}=await sb.functions.invoke('admin-users',{body});if(error||data?.error)throw new Error(data?.error||error.message);return data};
 function resetForm(){userForm.reset();userForm.elements.user_id.value='';userFormTitle.textContent='Create User';userSave.textContent='Create & Activate User';userCancel.classList.add('d-none');invitationOption.classList.remove('d-none');passwordHelp.textContent='Minimum 8 characters. The user can sign in immediately.';syncInvitation()}
 function syncInvitation(){const editing=!!userForm.elements.user_id.value,inviting=!editing&&sendInvitation.checked;userPassword.disabled=inviting;userPassword.required=!editing&&!inviting;userPassword.placeholder=editing?'Leave blank to retain existing password':inviting?'Invitation recipient will set password':'Minimum 8 characters'}
 sendInvitation.onchange=syncInvitation;userCancel.onclick=resetForm;
 async function load(){const {data:members,error}=await sb.from('tenant_members').select('user_id,role,status').eq('tenant_id',s.tenantId);if(error)return ua(error.message,'danger');const ids=(members||[]).map(x=>x.user_id);let profiles=[];if(ids.length){const {data:profileRows,error:profileError}=await sb.from('user_profiles').select('user_id,full_name,email').in('user_id',ids);if(profileError)return ua(profileError.message,'danger');profiles=profileRows||[]}users=(members||[]).map(x=>({...x,user_profiles:profiles.find(p=>p.user_id===x.user_id)||null}));userRows.innerHTML=users.map(x=>{const p=profile(x)||{},active=x.status==='active';return `<tr><td>${esc(p.full_name||'—')}</td><td>${esc(p.email||'—')}</td><td>${esc(x.role)}</td><td><span class="badge bg-${active?'success':'secondary'}">${esc(x.status)}</span></td><td><div class="d-flex gap-1 flex-wrap"><button class="btn btn-sm btn-outline-primary edit-user" data-id="${x.user_id}">Edit</button><button class="btn btn-sm btn-outline-${active?'warning':'success'} status-user" data-id="${x.user_id}" data-status="${active?'inactive':'active'}">${active?'Deactivate':'Activate'}</button><button class="btn btn-sm btn-outline-danger delete-user" data-id="${x.user_id}">Delete</button></div></td></tr>`}).join('');
  document.querySelectorAll('.edit-user').forEach(b=>b.onclick=()=>{const x=users.find(u=>u.user_id===b.dataset.id),p=profile(x)||{};userForm.elements.user_id.value=x.user_id;userForm.elements.name.value=p.full_name||'';userForm.elements.email.value=p.email||'';userForm.elements.role.value=x.role;userForm.elements.password.value='';userFormTitle.textContent='Edit User';userSave.textContent='Save User';userCancel.classList.remove('d-none');invitationOption.classList.add('d-none');passwordHelp.textContent='Leave password blank to keep the existing password, or enter a new password to reset it.';syncInvitation();scrollTo({top:0,behavior:'smooth'})});
  document.querySelectorAll('.status-user').forEach(b=>b.onclick=async()=>{try{const data=await invoke({action:'set_user_status',tenant_id:s.tenantId,user_id:b.dataset.id,status:b.dataset.status});ua(data.message);await load()}catch(error){ua(error.message,'danger')}});
  document.querySelectorAll('.delete-user').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this user from the organisation?'))return;try{const data=await invoke({action:'delete_user',tenant_id:s.tenantId,user_id:b.dataset.id});ua(data.message);resetForm();await load()}catch(error){ua(error.message,'danger')}})}
 userForm.onsubmit=async e=>{e.preventDefault();userSave.disabled=true;const p=Object.fromEntries(new FormData(userForm));try{const editing=!!p.user_id,body={action:editing?'update_user':'create_user',tenant_id:s.tenantId,name:p.name.trim(),email:p.email.trim(),role:p.role,password:p.password||'',user_id:p.user_id||undefined,send_invitation:!editing&&p.send_invitation==='on'};const data=await invoke(body);ua(data.message);resetForm();await load()}catch(error){ua(error.message,'danger')}finally{userSave.disabled=false}};
 resetForm();await load()});
